### ISSUE TITLE
Chokidar's outputs `/c: /c: is a directory`, doesn't run command.

### ISSUE THREAD

**Issue by romainl** [kimmobrunfeldt/chokidar-cli#15]
Hi, I'm currently trying to use chokidar via chokidar-cli to watch and build my JS both on Mac OS X and on Windows.

Software versions:

Mac OS X 10.10.4
* node 4.1.1
* npm 2.14.4
* chokidar-cli 1.1.0

Windows 7
* node 4.2.1
* npm 2.14.7
* chokidar-cli 1.1.0
* mingw32 provided by the latest Git for Windows

On Mac OS X, the paths are correctly watched and, although events are reported twice, they are all reported and the specified command is executed without problems. So, despite the weird double report part — which is supposed to be fixed — I'm pretty satisfied.

On Windows 7, the paths are correctly watched, the events are correctly reported but the specified command is never executed and I always get the same puzzling output: `/c: /c: is a directory`.

This is the npm script I use:

    "chok": "chokidar \"source/js/\" -c \"npm run js:dev\""

and this is how I would call it on its own:

    $ npm run chok

It is supposed to be used as part of a larger "system" but, whether it is used as part of that "system" or on its own, the outcome is always the same.

I've tried many quoting strategies and also tried `--command` to no avail. I've also tried to make it execute dummy commands like `-c \"echo 1\"` or `-c \"npm run foo\"` with no change.
 
When I leave out the `-c ...` part, chokidar correctly prints the changed file and doesn't output that mysterious `/c: /c: is a directory`.

**Comment by kimmobrunfeldt** [comment]
Thanks for reporting this. I haven't seen duplicate events fired on my OS X. If you can dig up more about that issue, it would be great.

About the Windows issue, chokidar-cli detects the underlying shell here: https://github.com/kimmobrunfeldt/chokidar-cli/blob/df8828fed2a520ff4acdedd42f8dd2c00f6a7c99/utils.js#L6-L10. The detection is apparently failing in your case. 

The detection is needed because we are passing the command argument to the platform shell:
* `cmd.exe /c "your command"` 
* `bash -c "your command"

I'm not sure which is the correct flag to use with minigw shell. To fix this, I see a few options:

1. Improve the shell detection
2. Provide a new cli argument for chokidar-cli, which would allow users to change the argument passed to the underlying shell. E.g. `chokidar 'source/js/' -c 'npm run js:dev' --shell-execute-arg '-c'`

**Comment by romainl** [comment]
Thanks for your reply.

When run directly in the mingw shell, `cmd.exe /c "dir"` outputs the following:

     Volume in drive C has no label.
     Volume Serial Number is E0CE-337D

     Directory of C:\Users\IEUser\Desktop\f6-starter-kit

    24/10/2015  13:52    <DIR>          .
    24/10/2015  13:52    <DIR>          ..
    27/09/2015  17:28               429 bower.json
    24/10/2015  00:44    <DIR>          build
    23/10/2015  14:21               502 cscope.out
    24/10/2015  00:49    <DIR>          node_modules
    24/10/2015  13:51             2▒195 npm-debug.log
    24/10/2015  13:52             4▒547 package.json
    23/10/2015  19:01            12▒702 README.md
    24/10/2015  00:45    <DIR>          scripts
    24/10/2015  00:45    <DIR>          source
                   5 File(s)         20▒375 bytes
                   6 Dir(s)  126▒248▒226▒816 bytes free

**Comment by romainl** [comment]
var EXECUTE_OPTION = process.env.COMSPEC !== undefined ? '/c' : '-c';

In mingw, both `COMSPEC` and `SHELL` are defined so the line above always sets the variable to `/c`.

I think that something like this should work:

    var EXECUTE_OPTION = process.env.COMSPEC !== undefined && process.env.SHELL === undefined ? '/c' : '-c';

**Comment by kimmobrunfeldt** [comment]
Yeah this seems like a good fix. Lets' move further discussion to PR: https://github.com/kimmobrunfeldt/chokidar-cli/pull/16

I created another issue about the lack of user customization over the shell flag: https://github.com/kimmobrunfeldt/chokidar-cli/issues/18
