### ISSUE TITLE
$PATH not set correctly after 1.0.1

### ISSUE THREAD

**Issue by kettuniko** [kimmobrunfeldt/chokidar-cli#9]
After the 1.0.1 release, $PATH variable is not set correctly, thus causing problems if node binaries are not located somewhere in 'default' $PATH. System: OSX with ZSH

Unfortunately I couldn't figure out what's actually wrong with the release, but here's some debug help: 

`export PATH=/path/to/somewhere/bin:$PATH`

`env`
 => PATH=/path/to/somewhere/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
:sunglasses: 

`npm install chokidar-cli@1.0.0`
`touch some-file-to-watch.txt`
`node_modules/.bin/chokidar 'some-file-to-watch.txt' -c 'env'`
 => PATH=/path/to/somewhere/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
:sunglasses:  

`npm install chokidar-cli@1.0.1`
`node_modules/.bin/chokidar 'some-file-to-watch.txt' -c 'env'`
 => PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
:weary:

**Comment by kimmobrunfeldt** [comment]
Thanks for reporting this. The change from 1.0.0 -> 1.0.1 was to use system's shell to execute the commands instead of just `child_process.spawn` function to support more shell features like `&&`. This apparently broke your use case.

I'll try get environment variables from the original shell context passed to the newly spawned shell. Not sure how yet.

**Comment by kimmobrunfeldt** [comment]
Reasoning for why I did "only" a patch release: To my mind this change didn't introduce any breaking changes or new features to the API. I think the newly introduced behavior was the expected behavior from the beginning. Therefore the previous behavior which did not support system shell features, was a bug.

**Comment by kimmobrunfeldt** [comment]
After testing this a bit. It seems like a bug with `/bin/zsh`.

**Works:**

```bash
SHELL=/bin/bash chokidar '*' -c 'echo $PATH'
```

**Doesn't work**

```bash
SHELL=/bin/zsh chokidar '*' -c 'echo $PATH'
```

Please open issue to https://github.com/robbyrussell/oh-my-zsh
